universal:
  prefix: '<extra_id_6>'
  end: '<extra_id_5>'
entity:
  instructionformat: 'Schema'
  context_left: 'None'
  context_right: 'None'
  context_mid: 'None'
  inputformat: "<extra_id_4> {text}"
  prefix: '<extra_id_6>'
  end: '<extra_id_5>'
  labelformat: 'temp' # temp, tanl, sel
relation:
  instructionformat: 'Schema'
  context_left: 'None'
  context_right: 'None'
  context_mid: 'None'
  inputformat: "<extra_id_4> {text}"
  prefix: '<extra_id_6>'
  end: '<extra_id_5>'
  labelformat: 'temp' # temp, tanl, sel